### ISSUE TITLE
Back & Right endstops don't trigger hold

### ISSUE THREAD

**Issue by flouSH** [bkubicek/Marlin#11]
Once the endstop triggered on the back and right of the UM won't stop the steppers anymore.

The fix previously done by Bradley isn't included in the latest commit from my perspective. Would be nice, if Bradley or anybody else could include the respective lines of code.

Thanks,
Florian

**Comment by bradleyf** [comment]
Ok, I put it back in.

**Comment by flouSH** [comment]
Thanks Bradley! Works like a charm. Hopefully it stays in this time ;)
