### ISSUE TITLE
interupt routine "busy" got triggered?

### ISSUE THREAD

**Issue by lampmaker** [bkubicek/Marlin#12]
The stepper interrupt routine has a "busy" provision that makes sure it leaves the routine if it has been been triggered while still inside the routine. (~line 2070  I believe).  I haven't checked ,but  I wonder: 
- does it ever get triggered (at high speeds for instance?) 
- If it got triggered once, it probably means the speed should be reduced, as it will likely continue to trigger until the speed goes down.
- If the timer is set to 30 microseconds, but the routine takes 35, it will trigger busy at 30 microseconds and then enter the routine again at the next "tick" , after another 30 if I understand things correctly.   Which would mean the total time is 60 microseconds between pulses and the  speed is -suddenly- reduced by 50% if it exceeds the max limit.    Do I understand this correctly?

**Comment by bkubicek** [comment]
no, i don't believe so. From my, although limited atmel experience, a running timer interrupt blocks all further interrups, until it returns. Also, I tried to re-enable the interrupts to circumvent this, in the same manner than in marlin, however it never ever worked. But, on the other hand, mega2560 could be different
