### ISSUE TITLE
M84 activates extruder stepper motor

### ISSUE THREAD

**Issue by flouSH** [bkubicek/Marlin#14]
Instead of deactivating the extruder stepper it's powered up when receiving the M84 Gcode command. Most likely a small typo somewhere ;)

Thanks for fixing!

**Comment by bradleyf** [comment]
What print software are you using?  I'm not seeing this under PrintRun.    

I remember someone saying that RepG sends both an M18 and M84 from the control panel.

**Comment by flouSH** [comment]
Hi Bradley, you're right: Normally I use RepG25, but I now setup Printrun and I'm seeing the same behavior. 
Following scenario: Fire up Printrun. Move X by 10, move Y by 10, move Z by 10, don't extrude. Check if steppers are activated (X,Y,Z) and the extruder stepper is inactive as expected. CHECK! 

Then type 'M84' and send off to the machine. Now check again the steppers: X,Y,Z inactive, extuder ACTIVE! Can you confirm this with Printrun or RepG? I use the latest 0.9.3 master branch compile. Probably you fixed it already in the experimental branch by coincidence?!

**Comment by bradleyf** [comment]
I can't reproduce this.  It works perfectly under the latest PrintRun, using your instructions.  Firmware code looks good too.

**Comment by flouSH** [comment]
hi bradley, just checked it with the 'experimental branch' (https://github.com/bkubicek/Marlin/tree/experimantal) and there you're right. Everything works smoothly with M84!

But I can reaffirm: Within the 'master branch' (https://github.com/bkubicek/Marlin) there has to be a bug. Anybody else can please confirm this?

It's nothing big, just want to point my finger on inconsistencies that everybody knows how to deal with the different branches, etc.

Thanks for your effort! 
Flo

**Comment by bradleyf** [comment]
Fixed!

**Comment by flouSH** [comment]
Now you've got the bug. Thanks a lot :)
