### ISSUE TITLE
Max feedrate 240?  // acceleration

### ISSUE THREAD

**Issue by lampmaker** [bkubicek/Marlin#21]
in configuration.h:

What is the max feedrate number of 240 based on?
If it's based on the max frequency the firmware can handle, it should probably be linked to the axis_steps_per_unit
Alternatively, we might make it a variable that can be overruled with M203 X500 Y500 etc. for instance

Also, I believe the max_acceleration_units_per_sq_second is only used as the default/initial acceleration, correct?   Perhaps it should be renamed.  I don't think it is the max. 

After some experiments, it came clear to me that the float acceleration is actually the maximum that can be set. It overrules the max_acceleration_units_per_sq_second.

So, at least we should change the numbers, bump up the float acceleration and set max_acceleration to 4000 or so.

**Comment by bradleyf** [comment]
Lampmaker:

Please download and use SmartGit -- it's free (http://www.syntevo.com/smartgit/index.html) to push your commits to the repository, that way your line endings will be adjusted and we'll all be able to see only what specific changes you made.  
Otherwise it's hard to tell when it shows the whole file being replaced.

**Comment by lampmaker** [comment]
the max feedrate number acts odd.  When I increase it to 800_60 or more, motion slows down tremendously.  500_60 still works fine.   I know a max feedrate of 800 is mostly theoretical, but at least it should operate correctly if the actual feedrate is lower.

**Comment by lampmaker** [comment]
I am using smartgit, though I am a complete noob at git (wished I had discovered much earlier, though).  Perhaps a setting in smartgit is screwed up somewhere? 

Found this: http://help.github.com/line-endings/  I will do this, delete all my local files and clone the git again.  Hope that sets things straight.
