### ISSUE TITLE
Change steps per unit on the way

### ISSUE THREAD

**Issue by hurzl** [bkubicek/Marlin#29]
If I change default steps per unit  for E by "M92 Exx" in the middle of a print, it tries to catch up the absolute amount by extruding or retracting. I think the firmware should react to the command by recalculating the so-far made absolute steps?

**Comment by bkubicek** [comment]
I thought that I had fixed this already. Maybe tonight.

**Comment by bkubicek** [comment]
fixed in this commit:
https://github.com/bkubicek/Marlin/commit/81202a8d303a848fc99c29a1f817a727f84450b1
