### ISSUE TITLE
Homing Problem

### ISSUE THREAD

**Issue by tatoogoo** [bkubicek/Marlin#32]
Hi, I have set up Marlin as the firmware on my new Prusa Mendel. Driving from a Macbook Pro via ReplicatorG and using an Arduino 1280 Mega + RAMPS 1.2. I seem to have an issue with homing.
I have noticed that, when I use a script saying 'G1 X-300 Y-300 F300' to home the X and Y axes, whichever limit switch trips first ends the command. i.e. if X reaches its limit switch while Y is only half way there, both axes will stop and do the 'back off and return to switch' where they are - with X on its switch but Y some way away. Is this a problem with the Marlin firmware?

**Comment by tatoogoo** [comment]
Ok, I've decided that this is a wetware fault on my part and I've now understood what is happening. thanks.

**Comment by ErikZalm** [comment]
Hello,

For homing you can use G28 X Y Z
If you hit an endstop with normal moves it is an error. The firmware stays safe by stopping the current movement.

Best regards,

Erik van der Zalm
