### ISSUE TITLE
compilation error with latest arduino (0024)

### ISSUE THREAD

**Issue by maybites** [bkubicek/Marlin#34]
Code doesnt compile with the latest arduino (built 0024):

In file included from Marlin.cpp:1:
Marlin.h:6:22: error: WProgram.h: No such file or directory
In file included from Marlin.cpp:1:
Marlin.h:48: error: variable or field 'manage_inactivity' declared void
Marlin.h:48: error: 'byte' was not declared in this scope
Marlin.h:112: error: variable or field 'kill' declared void
Marlin.h:112: error: 'byte' was not declared in this scope
In file included from Marlin.cpp:46:
streaming.h:28: error: expected initializer before '&' token
streaming.h:50: error: expected initializer before '&' token
streaming.h:68: error: expected initializer before '&' token
streaming.h:79: error: expected initializer before '&' token
In file included from Marlin.cpp:123:
SdFat.h:285: error: conflicting return type specified for 'virtual void SdFile::write(uint8_t)'
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Print.h:48: error:   overriding 'virtual size_t Print::write(uint8_t)'
In file included from Marlin.cpp:249:
EEPROM.h: In function 'void StoreSettings()':
EEPROM.h:54: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h: In function 'void RetrieveSettings(bool)':
EEPROM.h:82: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:100: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:102: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:103: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:104: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:105: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:106: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:107: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:108: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:109: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:110: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:111: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:113: error: no match for 'operator<<' in 'Serial << "echo: "'
EEPROM.h:114: error: no match for 'operator<<' in 'Serial << "echo: "'
Marlin.cpp: In function 'void setup()':
Marlin.pde:-1: error: no match for 'operator<<' in 'Serial << "echo: "'
Marlin.cpp: In function 'void process_commands()':
Marlin.pde:-1: error: no match for 'operator<<' in 'Serial << "echo: "'
Marlin.pde:-1: error: no match for 'operator<<' in 'Serial << "echo: "'
Marlin.pde:-1: error: no match for 'operator<<' in 'Serial << "echo: "'
Marlin.cpp: In function 'void __vector_12()':
Marlin.pde:-1: error: no match for 'operator<<' in 'Serial << "echo: "'

**Comment by bkubicek** [comment]
you are one the wrongs branch, i think. Please checkout Marlin_v1

**Comment by bkubicek** [comment]
you are even on the wrong trunk. Please have a look here:
https://github.com/ErikZalm/Marlin/tree/Marlin_v1

**Comment by maybites** [comment]
its confusing, but if you say so :-) I was following the links from this page (chapter Variant: Compile and Upload a Firmware from Source): http://wiki.ultimaker.com/How_to_upload_new_firmware_to_the_motherboard. please excuse my ignorance regarding git and its branch and trunking...
