### ISSUE TITLE
repetitive clicking

### ISSUE THREAD

**Issue by bkubicek** [bkubicek/Marlin#5]
Citation Joel:

> Another very strange finding of mine is: After a print when I leave
> the steppers activated my X-stepper starts to click (loose steps
> without even moving). The active cooling on the regulators and on the
> stepper itself are still active though. HOW can it happen, that
> without printing this stepper gets this hot? Please try to check this
> with your machines and have a close watch on hotter steppers due  to
> some firmware bug (my impression is that since Marlin, the steppers
> get hotter faster, with just idling - I'm not talking about the
> printing itself).

from Bernhard:
Every 0.5 to 1 second the extruder looses its holding power. It hence clicks. Possibly its the same for other Steppers too.
Probably non-lcd related, as also present with lcd disabled.
Could be some residual watchdog timer thing, that however should be disabled du to Arduino stk500 bootloader quirks with Watchdog.

**Comment by bradleyf** [comment]
Likely the LCD updates.

**Comment by bkubicek** [comment]
No, it was my extruder stepper driver that went into periodic thermal shutdown. Not a firmware issue at all...
