### ISSUE TITLE
Configuration H

### ISSUE THREAD

**Issue by jetguy** [bkubicek/Marlin#9]
Shouldn't the max axis for an Ultimaker be 210mm all the way around in config.h? 
Anyway to may that a switch when board type 7 is selected?
# define min_software_endstops false //If true, axis won't move to coordinates less than zero.
# define max_software_endstops true  //If true, axis won't move to coordinates greater than the defined lengths below.
# define X_MAX_LENGTH 200
# define Y_MAX_LENGTH 200
# define Z_MAX_LENGTH 100

Should be:
# define min_software_endstops false //If true, axis won't move to coordinates less than zero.
# define max_software_endstops true  //If true, axis won't move to coordinates greater than the defined lengths below.
# define X_MAX_LENGTH 210
# define Y_MAX_LENGTH 210
# define Z_MAX_LENGTH 210

**Comment by bradleyf** [comment]
You're probably right.   Most of us are not printing anything that large on this "experimental" firmware.

**Comment by bkubicek** [comment]
done. However, I saw no change in behaviour...

**Comment by jetguy** [comment]
Thanks, again, it's just my understanding of what a setting does VS what it actually does.
